internal/agent/agent.go, internal/database/database.go, internal/database/database_test.go, internal/database/writer_test.go, internal/scheduler/node.go, internal/scheduler/scheduler.go
Hi, I would like to execute the same DAG in multiple instances in parallel using containers, and gather the dat and log files from all runs in one common place (same as it is now under ~/.dagu).
This pull request adds request id to all file names to make them unique, and milliseconds for more precise tracking.
I am not sure about the change in Agent.Run() method though. It is now somewhat ugly (calling setupRequestId() before init()). If you see better way how to handle this point, I would be glad to change it.
Thanks, Lukas
=> Unique dat and log file names

README.md, internal/config/config.go, internal/config/definition.go, internal/config/step.go, internal/scheduler/node.go, internal/scheduler/node_test.go, internal/scheduler/scheduler.go, internal/scheduler/scheduler_test.go
Example:
```yaml
name: example
steps:
- name: step 1
command: "bash"
script: |
cd /tmp
echo "hello world" > hello
cat hello
output: RESULT
- name: step 2
command: echo ${RESULT} # hello world
depends:
- step 1
```
=> feat: run code snippet

cmd/dagu.go, cmd/version.go, cmd/version_test.go
I added `version` subcommand to print version on stdout.
=> feat: Add version subcommand that can tell the current build version

README.md, internal/config/config.go, internal/config/definition.go, internal/config/step.go, internal/scheduler/node.go, internal/scheduler/scheduler.go, internal/scheduler/scheduler_test.go
Added interval sec config to `retryPolicy`.
Example:
```yaml
steps:
- name: task1
command: main.py
retryPolicy:
limit: 2
intervalSec: 5
```
=> feat: Added retry interval sec config

internal/config/config.go, internal/config/config_test.go, internal/config/definition.go, internal/config/loader.go, internal/models/status_test.go, internal/reporter/reporter.go, internal/reporter/reporter_test.go, tests/config/.dagu/config.yaml, tests/testdata/config_no_overwrite.yaml, tests/testdata/config_overwrite.yaml
Allow users to choose whether or not to send mail on failure with individual DAGs by overriding the `MailOn` settings.
=> feat: overwrite global setting with individual DAG config

admin/src/components/DAGTable.tsx
=> feat: Sort the DAG table on the Web UI in case-insensitive `Name` order by default

admin/src/components/DashboardTimechart.tsx
=> feat: make time chart graph scrollable on Dashboard page

internal/config/config.go, internal/config/config_test.go, internal/runner/job_test.go
=> Allow parameters field contains spaces inside each parameter

internal/config/config.go, internal/models/node_test.go, internal/scheduler/node.go, internal/scheduler/node_test.go, internal/scheduler/scheduler_test.go, internal/utils/utils.go, internal/utils/utils_test.go
=> Fix parameter parsing issue

cmd/dagu.go, cmd/scheduler.go, cmd/server.go, internal/admin/config.go, internal/admin/config_test.go
=> Load admin config for all commands before action

cmd/dagu.go, cmd/server_test.go, internal/admin/config.go, internal/admin/config_test.go, internal/admin/definition.go, internal/admin/handlers/dag.go, internal/admin/handlers/html.go, internal/admin/handlers/list.go, internal/admin/loader.go, internal/admin/loader_test.go, internal/admin/routes.go, internal/settings/settings.go, internal/settings/settings_test.go
This PR closes #248 
This change disables env config below:
- DAGU__DATA
- DAGU__LOGS
- DAGU__SUSPEND_FLAGS_DIR
- DAGU__ADMIN_CONFIG
- DAGU__ADMIN_PORT
- DAGU__ADMIN_NAVBAR_COLOR
- DAGU__ADMIN_NAVBAR_TITLE
- DAGU__ADMIN_LOGS_DIR
- DAGU__ADMIN_DAGS_DIR
The user can still set the group of values below within the global config file:
- DAGU__ADMIN_LOGS_DIR
- DAGU__ADMIN_PORT
- DAGU__ADMIN_NAVBAR_COLOR
- DAGU__ADMIN_NAVBAR_TITLE
example:
```yaml
logs: /var/dagu/
port: 8080
navbarColor: red
navbarTitle: production
```
=> all: permit to read config from yaml not from env

internal/admin/config_test.go, internal/admin/loader.go
Unused key error in admin config should not stop jobs.
=> internal/admin: no error on decode when there's unused keys

admin/index.html, admin/src/Layout.tsx, admin/src/components/atoms/BorderedBox.tsx, admin/src/components/molecules/DAGTable.tsx, admin/src/components/molecules/Graph.tsx, admin/src/consts.ts, admin/src/styles/styles.css, examples/specialchar.yaml, internal/scheduler/node_test.go, internal/utils/utils.go
=> fix specialchar parsing issue

admin/src/components/molecules/DAGAttributes.tsx, admin/src/components/molecules/DAGSpecErrors.tsx, admin/src/pages/dags/dag/index.tsx, admin/src/pages/dags/index.tsx, examples/named_params.yaml
=> admin- web small issues

README.md, cmd/dagu.go, cmd/scheduler.go, cmd/server.go, cmd/server_test.go
example: `dagu server --host=10.0.100.101 --port=80 --dags=/home/var/dags`
Note: If those options are specified, the same field value in admin config will be ignored.
=> Add `host`, `port`, `dags` option to the `server` command

README.md, internal/dag/dag.go, internal/dag/dag_test.go
Example:
```yaml
schedule:
start:
- "0 0 * * *"
- "12 0 * * *"
stop:
- "5 0 * * *"
- "17 0 * * *"
```
=> internal/dag: feat: Allow multiple start/stop schedule

README.md, internal/dag/dag.go, internal/dag/definition.go, internal/dag/step.go, internal/scheduler/node.go, internal/scheduler/node_test.go
Closes #312 
Example:
```yaml
steps:
- name: output error file
command: "echo error message >&2"
stderr: "/tmp/error.txt"
```
=> Add `stderr` field to separate stderr output from the normal log file.

cmd/start.go
https://github.com/yohamta/dagu/issues/279#issuecomment-1237603177
Like shellworlds pasre string be quoted as raw-string.
```
dagu start --params "a b" demo.yaml
expect:
$1: a
$2: b
but:
$1: 'a b'
```
So we should trim the `"`.
=> fix start dag with params

README.md, cmd/dagu.go, cmd/restart.go, cmd/restart_test.go, cmd/testdata/restart.yaml, internal/controller/controller.go, internal/controller/controller_test.go, internal/controller/testdata/restart.yaml, internal/dag/dag.go, internal/dag/dag_test.go, internal/dag/definition.go, internal/executor/command.go, internal/runner/entry.go, internal/runner/job.go, internal/runner/runner_test.go
=> Add `restart` feature

.goreleaser.yaml, go.mod
close https://github.com/yohamta/dagu/issues/322
=> add release armv7

README.md, agent.go, examples/email_example.yaml, examples/minimal.yaml, internal/dag/dag.go, internal/dag/definition.go, internal/dag/mail.go, internal/mailer/mailer.go
=> Add auth stmp mailer

README.md, examples/README.md, examples/exec_docker_image.yaml
Add more explanation about running Docker container.
=> update examples for docker container

internal/executor/http.go
I would like to use environment variables in the HTTP script such as $API_KEY.
@Arvintian If you have any concerns with this change, please let me know.
=> Update HTTP Executor to expand env

cmd/commands.go
Those descriptions seemed to be swapped.
=> fix: server command host & port description swapped

internal/scheduler/graph.go
有 spec 如下:
```yaml
steps:
- name: a
command: echo hello
- name: b
command: echo hello
depends:
- a
- name: c
command: echo hello
depends:
- b
- name: d
command: echo hello
depends:
- b
- name: e
command: echo hello
depends:
- f
- name: g
command: echo hello
depends:
- f
- b
- name: h
command: echo hello
depends:
- e
- g
- f
- name: i
command: echo hello
depends:
- f
- name: j
command: echo hello
depends:
- f
- name: f
command: echo hello
depends:
- d
- name: k
command: echo hello
depends:
- b
- name: o
command: echo hello
depends:
- b
- name: p
command: echo hello
depends:
- b
- name: q
command: echo hello
depends:
- b
- f
- k
- o
- p
```
当前版本(v1.0.3)，提示 `cycle detected`：
本次提交修复后：
=> fix: 修复 DAG 环路检测

internal/dag/builder.go, internal/dag/definition.go, internal/utils/utils.go
implements #429 
Examples:
```
functions:
- name: my_function
params: param1 param2
command: python main.py $param1 $param2
steps:
- name: step 1
call:
function: my_function
args:
param1: 1
param2: 2
```
Notes
- If the general idea is good, I will implement the test
=> Add support for user-defined functions and call field in YAML format

docs/source/auth.rst
Noticed a difference in the documentation as compared to the expected environment variables for the authentication. Updated the documentation to reflect the correct variables and file name.
This PR has been opened after a discussion in Issue #421
=> docs: updated env vars for authentication

docs/source/config.rst
=> fix doc error

docs/source/yaml_format.rst
Hi!
I have added the missing field `depends` to docs.
=> The field `depends` is added to docs `Available Fields for Steps`

service/frontend/middleware/basic_auth.go, service/frontend/middleware/basic_auth_test.go, service/frontend/middleware/global.go, service/frontend/server/server.go
Resolves https://github.com/dagu-dev/dagu/issues/509
Skip basic auth when auth token is set
In addition, I also rename `basicAuth` to `authBasic` for naming consistency with `authToken`
=> Skip basic auth when auth token is set

service/frontend/middleware/basic_auth_test.go
Fix error when running `make go-lint`
```
➜  dagu git:(main) ✗ make go-lint
service/frontend/middleware/basic_auth_test.go:14:10: Error return value of `w.Write` is not checked (errcheck)
w.Write([]byte("OK"))
^
make: *** [Makefile:83: go-lint] Error 1
```
This error affects `make build`, so I think it is quite important to fix this
=> Fix linter error

cmd/common_test.go, cmd/dry.go, cmd/restart.go, cmd/retry.go, cmd/root.go, cmd/scheduler.go, cmd/server.go, cmd/start.go, cmd/start_all.go, cmd/status.go, cmd/stop.go, cmd/version.go
=> Fix command flag duplication issue

README.md
=> Small fixes to README.md formatting

internal/persistence/client/store_factory.go
As this issue: https://github.com/dagu-dev/dagu/issues/530
During the testing process, I found that the scheduler tried to find the directory "$HOME/. dagu/tags" when starting, but it did not create this directory. This can lead to a problem: the scheduler will not be able to start the watcher service when it cannot find this directory, but it will not exit itself. Therefore, when adding a cron task on the page, these cron tasks will not be scheduled. However, when users perform queries or add tasks on the page, the directory of dags will be automatically created. However, since it is not a hot load, the scheduler will not re read this directory, and subsequent watcher services will never start unless the scheduler is manually killed and restarted.
In summary, I believe that adding an …
=> Init dag dir

README.md, cmd/common_test.go, cmd/restart_test.go, cmd/retry.go, docs/source/yaml_format.rst, go.mod, go.sum, internal/agent/agent.go, internal/agent/agent_test.go, internal/config/config.go, internal/dag/builder.go, internal/dag/context.go, internal/dag/definition.go, internal/dag/step.go, internal/engine/engine_test.go, internal/engine/factory.go, internal/executor/mail.go, internal/executor/subworkflow.go, internal/persistence/interface.go, internal/persistence/local/dag_store.go, internal/scheduler/node.go, service/frontend/handlers/response/step.go, service/frontend/models/step_object.go, service/frontend/restapi/embedded_spec.go, service/scheduler/entry_reader/entry_reader_test.go, service/scheduler/factory.go, service/scheduler/fx.go, service/scheduler/job/job.go, swagger.yaml, ui/src/models/index.ts
This PR implements sub-workflow execution as discussed in #373
Example:
```yaml
steps:
- name: running sub-dag
run: sub_dag
params: "FOO=TEST" # optional
```
=> Add `run` and `params` field

internal/executor/http.go
http executor does not include query map when configured as documented
bug: key=value is excluded from request
```
steps:
- name: send POST request
command: POST https://foo.bar.com
executor:
type: http
config:
query: 
key: "value"
```
mapstructure does not read query into QueryParams.  
Rename QueryParams into Query to match yaml
Add debug resty option
=> Fix http query map. Add http console debug.

internal/dag/dag.go, internal/dag/dag_test.go
Ensures that we truncate task names to no more than 60 chars so they don't exceed the total length limit of 108 that's impose by unix.
Fixes: https://github.com/dagu-dev/dagu/issues/395
=> Fix issue with socket length > 108 due to long task names

ui/src/components/molecules/NodeStatusTableRow.tsx, ui/src/components/molecules/StartDAGModal.tsx
Fixes: https://github.com/dagu-dev/dagu/issues/594
Screenshots of before and after when using the same dag 
In the case of long params, the dialogue box is unusable and this is part of a fix to improve their usability.
This change limits each arg to one line and the params remain scrollable to allow for user editing.
For discussion:
1. Does this harm other use cases?
2. Is there a simpler way to accomplish the same ends?
I'm not stuck on this solution but I do see it re-enabling usability of the Start dialogue for cases where the params's value is long.
=> (ui) Improve UI when using long values in params

.goreleaser.yaml
This block allows for dagu to be run as a service under homebrew and it then allows the following commands:
```
brew services status dagu
brew services start dagu
brew services stop dagu
```
When the brew install happens, there is also a prompt to the user in case they want to enable the service or run directly.
The benefit here is that it enables dagu to be run as a background service automatically on startup and controlled via a centralized system.
The resulting local brew formula is:
```ruby
class Dagu < Formula
desc "A No-code workflow executor that runs DAGs defined in a simple YAML format"
homepage "https://github.com/dagu-dev/dagu"
version "1.13.1-next"
license "GNU General Public License v3.0"
on_macos do
if Hardware::CPU.intel?
url …
```
=> (feat) Add service block to goreleaser brew config

.goreleaser.yaml, README.md
Non-urgent but mild usability improvement on homebrew recipe and tap usage.
Related: https://github.com/dagu-dev/dagu/pull/597
With this change the homebrew formula can be installed as:
brew tap dagu-dev/dagu && brew install dagu
OR
brew install dagu-dev/dagu/dagu
Note: this takes advantage of conventions for naming in homebrew and requires setting up a repo of `dagu-dev/homebrew-dagu` which is then automatically referenced when doing `brew tap dagu-dev/dagu`.
Example when I try to do the brew tap command before anything is setup:
```
❯ brew tap dagu-dev/dagu
==> Tapping dagu-dev/dagu
Cloning into '/opt/homebrew/Library/Taps/dagu-dev/homebrew-dagu'...
remote: Repository not found.
fatal: repository 'https://github.com/dagu-dev/homebrew-dagu/' not found
```
I can't test it out, but I …
=> (feat) Publish homebrew formula to organization

ui/src/components/organizations/ExecutionLog.tsx
Reason: Ansi escape codes are intended to manipulate a terminal and when they're printed they make it more difficult to read the intended log content.
Current output: 
Desired output as represented by PR: 
Task definition:
```
steps:
- name: step1
command: bash $HOME/src/dagu/tester.sh
```
```bash
#!/usr/bin/env bash
set -eou pipefail
source $HOME/bin/lib/colors
echo -e "${gre}green text, ${mag}magenta text, ${coloroff}default"
echo -e "${gre}green text, ${mag}magenta text, ${coloroff}default"
echo -e "${gre}green text, ${mag}magenta text, ${coloroff}default"
echo -e "${gre}green text, ${mag}magenta text, ${coloroff}default"
echo -e "${gre}green text, ${mag}magenta text, ${coloroff}default"
echo -e "${gre}green text, ${mag}magenta text, ${coloroff}default"
....
```
$HOME/lib/colors is: …
=> (bug) Remove ansi escape codes from UI Log Display

docs/source/yaml_format.rst, internal/dag/executor/docker.go
Fixes #595
Users can now skip docker pull by passing `pull: false` in executor config
=> Add option to skip docker image pull

internal/dag/executor/docker.go
Fixes #610 
Status from docker executor is now correctly reported to Dagu on exit:
=> Propagate Docker container exit code

internal/dag/executor/docker.go
Fixes #611 
Stderr output from Docker container is now correctly captured by Dagu
=> Capture stderr from Docker container

internal/engine/engine.go, internal/engine/interface.go, internal/persistence/interface.go, internal/persistence/jsondb/store.go, internal/persistence/jsondb/store_test.go, internal/persistence/jsondb/writer_test.go, internal/persistence/local/dag_store.go, internal/util/utils.go, internal/util/utils_test.go
Resolves: #580
Add timezone information to the execution history data. The web UI currently now shows started / finished time with timezone in RFC3339 format.
=> Display execution startAt / finishedAt timezone on Web UI

ui/src/components/molecules/DAGTable.tsx
When a DAG has a custom name defined, the actions buttons on the DAG list page don't work as the frontend uses the custom name instead of the DAG file name to call the "Submit DAG Action" API (`POST /api/v1/dags/:name`).
For example, given a DAG namely `test.yaml` as below:
```yaml
name: Custom Name
steps:
- name: step1
command: echo hello
```
When the "Start the DAG" button is clicked from the DAG list page, the following API is called incorrectly:
`POST /api/v1/dags/Custom Name`.
Instead, `POST /api/v1/dags/test` should be called.
To fix it, I simply extract the DAG filename without the `.yaml` extention name from `data.DAGStatus.File`, and then use that as the `name` property on `DAGActions`.
=> fix: action buttons on the DAG list page don't work for DAGs with custom names

internal/dag/executor/docker.go
Fixes: #633 
The container is now cleanly removed if workflow is cancelled
```
time=2024-07-26T23:15:46.401+02:00 level=INFO msg="Stop request received"
time=2024-07-26T23:15:46.454+02:00 level=INFO msg="Sending signal to running child processes" signal=terminated
time=2024-07-26T23:15:46.456+02:00 level=INFO msg="Waiting for child processes to exit..."
2024/07/26 23:15:46 Sending terminated signal to run
time=2024-07-26T23:15:46.881+02:00 level=INFO msg="Step execution finished" step=run status=canceled
time=2024-07-26T23:15:46.881+02:00 level=INFO msg="Workflow execution finished" status=canceled
```
=> Remove container if workflow is cancelled

internal/client/client.go, internal/scheduler/entryreader.go, ui/src/components/molecules/LiveSwitch.tsx
I find that toggling DAG suspension (i.e. "live") from frontend doesn't work when the DAG has a custom name defined:
Similar to #625, the frontend fix is extracting the file basename with out the `.yaml` bit as the DAG ID, and pass that to the backend for toggling.
However, upon fruther inspection, I also found the backend rest API doesn't return the right suspension status on a DAG with custom name. Furthermore, the scheduler also assumes a DAG's "name" is always the filename when calling `client.IsSuspended()`. So I fixed those as well.
It looks like `DAG.Name` is used quite a few times when actually a `DAG.ID` should be used instead. Maybe we should consider adding a new `ID` field to the `DAG` struct, which always stores the YAML filename, while `DAG.Name` can be overwritten with a …
=> Fix toggling DAG suspension for DAGs with custom names

cmd/dry.go, cmd/start.go, internal/dag/builder_test.go, internal/test/setup.go
Resolves #635
**Overview**
This PR addresses an issue that `start` command fails to parse parameters when the parameters are enclosed in double quotes.
=> [#635] fix: Parameter does not work

ui/src/components/molecules/NodeStatusTableRow.tsx
Fixes an issue where if a step has the '&' character in its name, the step log will not load.
=> Fix log not loading when '&' in name

internal/dag/executor/ssh.go
support login in with password while executor config not contain ssh key
1. executor config change add password
2. result
step log file :
in my machine
=> ISSUE[584] ssh executor does not support login in password

internal/dag/executor/http.go
HTTP executor supports writing the HTTP response in JSON format.
```
{
"status_code": 200,
"headers": [
"xxx": "yyy"
],
"body": {
"some_field": "some_value"
}
}
```
HTTP executor config
Result
=> ISSUE[578] Add json bool configuration option to HTTP executor

internal/agent/agent_test.go
=> [ISSUE 657] Fix HTTP_HandleCancel in TestAgent_HandleHTTP was a flakey test

internal/agent/agent.go, internal/agent/agent_test.go, internal/agent/testdata/timeout.yaml, internal/dag/builder.go, internal/dag/dag.go, internal/dag/definition.go, internal/dag/scheduler/scheduler.go, internal/dag/scheduler/scheduler_test.go
Fixes: #565 
Modified to allow timeouts to be set for DAG task execution.
- As outlined in issue #565, when a timeout occurs, all steps are set to cancel status and the entire DAG is set to error status (failed).
- Output to the log to indicate that a step has been canceled.
```
time=2024-08-11T14:41:08.210+09:00 level=INFO msg="Workflow execution initiated" workflow=test2 requestID=0553ba38-1861-4a35-a0c5-5a9196e6f1ca logFile=/Users/kiyofumi.sano/.dagu/logs/start_test2.20240811.14:41:08.210.0553ba38.log
time=2024-08-11T14:41:08.213+09:00 level=INFO msg="Step execution started" step=step1
time=2024-08-11T14:41:08.214+09:00 level=INFO msg="Step execution started" step=step4
time=2024-08-11T14:41:08.214+09:00 level=INFO msg="Step execution started" step=step5 …
```
=> [ISSUE 565] Implement Timeout Configuration for DAG Tasks

docs/source/yaml_format.rst
=> [ISSUE 661] Add documentation about timeouts for DAG tasks

ui/src/components/molecules/DAGErrorSnackBar.tsx, ui/src/pages/dags/dag/index.tsx
1. make error text more noticeable
like :
=> [ISSUE #592] formatting of error text in web ui is not very noticeable

ui/src/components/molecules/DAGTable.tsx
=> ui: fix: DAG groups are not visible on UI

docs/source/docker-compose.rst
This pull request addresses an issue where both containers were running a scheduler, leading to DAGs being scheduled twice.
=> Add command to run server in docker compose file

internal/config/config.go, internal/frontend/frontend.go, internal/frontend/server/server.go, internal/frontend/server/templates.go, internal/frontend/templates/base.gohtml, ui/index.html, ui/src/App.tsx, ui/src/components/molecules/DAGTable.tsx, ui/src/models/index.ts
There is an issue if the server is running in a timezone (eg. UTC), but the client's browser timezone is in another timezone (eg. Australia/Sydney), the cron expression incorrectly shows the Next Run incorrectly.
Open on thoughts on the best way to get the server's timezone? Create an API endpoint? Open to feedback
=> fix: use the server timezone to parse the cron expression

Makefile, docs/source/config.rst, internal/config/config.go, internal/frontend/frontend.go, internal/frontend/server/server.go, internal/frontend/server/templates.go, internal/frontend/templates/base.gohtml, internal/scheduler/entryreader.go, internal/scheduler/entryreader_test.go, internal/scheduler/scheduler.go, internal/scheduler/scheduler_test.go, ui/index.html, ui/src/App.tsx, ui/src/components/molecules/DAGTable.tsx, ui/src/models/index.ts
This PR Adds the documentation about `tz` configuration via config file and environment variables. Also includes some refactoring regarding time zone handling.
- Added the documentation for `tz`
- Refactored the scheduler to use the specified timezone setting
- Refactored the environment config key to `DAGU_TZ`
=> Add documentation for the time zone configurations

Dockerfile, README.md, docs/source/docker-compose.rst, docs/source/docker.rst, examples/docker-compose.yaml
- chore: Updated the Dockerfile to set default `DAGU_TZ`
- docs: Updated the examples of `docker-compose.yaml` and `Dockerfile`
=> chore: update the Dockerfile & docs

.gitignore, internal/persistence/local/dag_store.go, ui/package.json, ui/src/App.tsx, ui/src/components/molecules/DAGPagination.tsx, ui/src/contexts/UserPreference.tsx, ui/src/pages/dags/index.tsx, ui/yarn.lock
This PR addresses #700 by improving the UI
- **Page Limit Input:** Added a text box for setting the page limit
- **Case-Insensitive Search:** Updated the DAG name search to be case-insensitive
=> [#700] Add Page Limit Input and Improve Case-Insensitive DAG Search

ui/package.json, ui/src/components/molecules/DashboardTimechart.tsx, ui/src/pages/index.tsx, ui/yarn.lock
Reimplemented the timeline chart due to outdated implementation. This update also includes adjustments to ensure proper handling of the server-side timezone.
=> ui: Reimplement Timeline Chart and Adjust Server Timezone Handling

ui/src/models/index.ts
Related to https://github.com/dagu-org/dagu/issues/706, when using the `CRON_Z` in an expression
```
CRON_TZ=Asia/Tokyo 0 6 * * *
```
The `/dags`  page doesn't load, see below
The fixed version
=> fixed bug when using the CRON_TZ= cron expression

.vscode/launch.json, docs/source/config.rst, docs/source/scheduler.rst, docs/source/yaml_format.rst, internal/dag/builder.go, internal/dag/dag.go, internal/dag/definition.go, internal/scheduler/entryreader.go, internal/scheduler/job.go, internal/scheduler/mocks_test.go, internal/scheduler/scheduler.go
=> [#709] feat: Add `skipIfSuccessful`

docs/source/config.rst
From my experience the default paths for `DAGU_LOG_DIR` and `DAGU_DATA_DIR` are incorrect?
Not sure about `DAGU_ADMIN_LOG_DIR`...
If I'm wrong, feel free to close this PR :)
=> fix: incorrect paths in config docs

docs/source/scheduler.rst
I have added docs to highlight the support for time zone expressions
=> docs: added docs for CRON_TZ

docs/source/config.rst, docs/source/scheduler.rst, internal/frontend/middleware/global.go
This PR resolves a redirect loop issue when accessing Dagu through an Nginx reverse proxy at http://localhost/dagu.
The problem arose from Dagu's basePath configuration and the Nginx proxy settings. Accessing Dagu via the proxy resulted in an infinite redirect loop.
**Reproduction Steps:**
The issue can be reproduced with the following Nginx and Dagu configurations:
```nginx
server {
listen       80;
server_name  localhost;
location /dagu/ {
proxy_pass http://localhost:8080/;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
}
```
```yaml
port: 8080
basePath: /dagu
```
This PR fixes the issue by modifying HTTP handler for handling `basePath`. Testing confirms that Dagu is now accessible through the proxy at …
=> fix: Resolve redirect loop when accessing /dagu through local nginx

internal/frontend/middleware/global.go
Related: #720 
**Change overview**
- Remove the unnecessary protection against the proxy misconfiguration
=> Refactor: simplify request handling further

Dockerfile, docs/source/docker-compose.rst, docs/source/executors.rst, entrypoint.sh, examples/docker-compose.yaml
Closes #715 
This work significantly changes the Dockerfile and the required docker-compose.yaml configuration. 
The changes include
- Moving to a more idiomatic `/config` directory using `DAGU_HOME`. This relies on the resolver.go behavior that places all files together when `appHomeEnv` is specified. 
- Introducing an `entrypoint.sh` file that does the following
- Sets up the docker group if DOCKER_GID is provided
- Updates the dagu user to the provided PUID and PGID if provided
- Tries to guess if the running container is using the previous recommended setup using `/home/dagu` inside the container - if so it uses it 
- Otherwise sets `DAGU_HOME=/config` if DAGU_HOME is not already set 
- Runs any scripts in `/etc/custom-init.d` during boot. This can be used to install things into the …
=> Improve Dockerfile to reduce amount of config needed in docker-compose

internal/config/config.go, internal/frontend/frontend.go, internal/frontend/server/server.go, internal/frontend/server/templates.go, internal/frontend/templates/base.gohtml, ui/index.html, ui/src/contexts/ConfigContext.tsx, ui/src/pages/index.tsx
Related to https://github.com/dagu-org/dagu/issues/721
This allows the max items returned on the dashboard page to be adjusted according to the number of DAGs.
It feels a little hacky, so open to further thoughts? 
What if we have an new API to aggregate the results? (to provide the values to the highlighted in green)
Or we filter the results based on time? (in red, sorry for the bad drawings) eg only show those that ran "today"
=> add support for default page

README.md, docs/source/config_remote.rst, docs/source/index.rst, go.mod, internal/config/config.go, internal/frontend/dag/handler.go, internal/frontend/frontend.go, internal/frontend/server/server.go, internal/frontend/server/templates.go, internal/frontend/templates/base.gohtml, ui/index.html, ui/src/App.tsx, ui/src/Layout.tsx, ui/src/components/molecules/CreateDAGButton.tsx, ui/src/components/molecules/DAGActions.tsx, ui/src/components/molecules/DAGEditButtons.tsx, ui/src/components/molecules/LiveSwitch.tsx, ui/src/components/organizations/DAGSpec.tsx, ui/src/contexts/AppBarContext.ts, ui/src/contexts/ConfigContext.tsx, ui/src/hooks/useDAGPostAPI.ts, ui/src/pages/dags/dag/index.tsx, ui/src/pages/dags/index.tsx, ui/src/pages/index.tsx, ui/src/pages/search/index.tsx
Resolves #730 
This PR implements support for managing multiple Dagu instances from a single UI, allowing users to monitor and control DAGs across different environments through a centralized interface.
**Changes**
- Add request proxying to support remote Dagu instances
- Implement remote node configuration via admin.yaml
- Add UI dropdown for instance selection
- Add documentation for setup
**Configuration Example**
```yaml
remoteNodes:
- name: "dev"                                # name of the remote node
apiBaseUrl: "http://localhost:8080/api/v1" # Base API URL of the remote node it must end with /api/v1
isBasicAuth: true              # Enable basic auth (optional)
basicAuthUsername: "admin"     # Basic auth username (optional)
basicAuthPassword: "secret"    # Basic auth password …
```
=> [#730] Add Remote-Node support

README.md, docs/source/yaml_format.rst, internal/cmdutil/cmdutil.go, internal/cmdutil/cmdutil_test.go, internal/digraph/assert.go, internal/digraph/builder.go, internal/digraph/builder_test.go, internal/digraph/command.go, internal/digraph/condition.go, internal/digraph/dag.go, internal/digraph/executor/command.go, internal/digraph/scheduler/node.go, internal/digraph/scheduler/node_test.go, internal/digraph/scheduler/scheduler_test.go, internal/digraph/spec.go, internal/digraph/step.go, internal/digraph/variables.go
Changes command execution to use shell (`$SHELL` by default) instead of direct execution. This enables proper handling of pipes and other shell features.
- Use shell for command execution
- Create `cmdutil` package for command parsing
- Allow explicit shell override via new `shell` field
```yaml
steps:
- name: step 1
command: echo hello world | xargs echo
shell: bash  # Optional, defaults to $SHELL
```
=> feat!: Use shell for running command execution

internal/cmdutil/cmdutil.go, internal/digraph/builder.go, internal/digraph/scheduler/node.go, internal/digraph/scheduler/scheduler.go, internal/digraph/scheduler/scheduler_test.go, internal/digraph/spec.go, internal/digraph/step.go, internal/persistence/model/status_test.go
- Enabled command substitution and environment variables for retry policy configuration
=> builder: Enable Command Substitution for RetryPolicy configuration

ui/src/components/atoms/StatusChip.tsx, ui/src/components/molecules/Graph.tsx, ui/src/components/organizations/DAGStatus.tsx, ui/src/pages/dags/dag/index.tsx
- Added workflow status on the top of the detail page
=> ui: Add status on top of the detail page

internal/digraph/builder_test.go, internal/digraph/params.go, internal/digraph/spec.go, internal/digraph/testdata/params_as_map.yaml, internal/digraph/testdata/params_as_map_override.yaml
Resolves #755 
Example:
```yaml
params:
- FOO: foo
- BAR: bar
- BAZ: "`echo baz`"
steps:
- name: step_1
command: |
echo ${FOO} ${BAR} ${BAZ}
```
=> [#755] dag: Support `params` as a list of key-value pairs

internal/persistence/local/dag_store.go
- Improved the DAG list API to optimize the performance of filtering DAGs by their names
=> api: improve search performance on the DAG List page

docs/source/schema.rst, docs/source/yaml_format.rst, internal/cmdutil/cmdutil.go, internal/cmdutil/cmdutil_test.go, internal/digraph/builder.go, internal/digraph/condition.go, internal/digraph/condition_test.go, internal/digraph/errors.go, internal/digraph/executor/command.go, internal/digraph/scheduler/node.go, internal/digraph/scheduler/node_test.go, internal/digraph/scheduler/scheduler_test.go, internal/digraph/spec.go, internal/digraph/step_context.go
=> [#768] dag: Support precondition as a shell command

internal/cmdutil/cmdutil.go, internal/digraph/condition.go, internal/digraph/condition_test.go, internal/digraph/context.go, internal/digraph/step_context.go
- Resolved an issue where `precondition.command` execution occurred after the expansion of environment variables, leading to incorrect outcomes.
=> digraph: fix: Do not expand env before command evaluation

internal/digraph/scheduler/node.go
=> digraph: update node.go

docs/source/contrib.rst
Fixes a rendering issue in the docs.
The Contribution Guide has an itemized list under the [Code Structure](https://dagu.readthedocs.io/en/latest/contrib.html#code-structure) heading. The final item (which covers `internal`) is rendering incorrectly.  This is due to the lack of an empty line between the item and the first sub-item, causing Docutils to parse the sub-items as part of the paragraph rather than as distinct block-level nodes.
=> Fixes itemized list in Contribution Guide

internal/test/setup.go
Resolves #804  
Tests:
- Running tests with `SHELL=bash`
```sh
SHELL=bash make test
```
=> test: set default shell for reproducible results

ui/src/components/molecules/DAGActions.tsx, ui/src/components/molecules/DAGDefinition.tsx, ui/src/components/molecules/DashboardTimechart.tsx, ui/src/components/molecules/Graph.tsx, ui/src/components/molecules/HistoryTable.tsx, ui/src/components/molecules/HistoryTableRow.tsx, ui/src/components/molecules/NodeStatusChip.tsx, ui/src/components/molecules/NodeStatusTable.tsx, ui/src/components/organizations/DAGSpec.tsx, ui/src/components/organizations/DAGStatus.tsx, ui/src/components/organizations/ExecutionHistory.tsx, ui/src/contexts/DAGStatusContext.ts, ui/src/hooks/useDAGPostAPI.ts, ui/src/pages/dags/dag/index.tsx
Issue: #796 
Changes:
- Fixed a bug in the UI that cached data incorrectly
- Removed unnecessary useMemo hooks
=> [#796] ui: Fix: history data some time wrongly ordered

docs/source/examples.rst, docs/source/executors.rst, docs/source/schema.rst, examples/execute_docker_image.yaml
Update docker examples, fix hello-world.ts comands and fix docker host examples 
Fixes #638
=> chore: Update docker examples (Fixes #638)

docs/source/examples.rst, internal/digraph/executor/mail.go, internal/digraph/executor/mail_test.go
Surface email attachments feature in mail executor and update docs.
=> chore: Email attachment testcase (Fixes #812)

Makefile
Fetch git tag and appended to LDFLAGS in Makefile. 
Improve dagu version command line output with github tags.
Fixes #816
=> Add git tags to dagu version (Fixes #816)

scripts/installer.sh
Checking out dagu  and tried using the `scripts/installer.sh` to download latest release from [Dagu Releases](https://github.com/dagu-org/dagu/releases)
Ran into a few bugs. First, a syntax error, then issues getting the correct URL to download the release file. 
Debugging/tested on an Ubuntu 24.10 system.
Syntax issue:
```
./installer.sh
Downloading the latest binary to the current directory...
Downloading Dagu v1.16.1...
./installer.sh: 43: Bad substitution
```
Current URL build method
```
"$RELEASES_URL/download/$VERSION/${FILE_BASENAME}_${VERSION:1}_$(uname -s)_${ARCHITECTURE}.tar.gz" 
```
The tweaks to get rid of syntax issue & the correct URL for the file on the releases page:
- `$(uname -s)` is giving `Linux` but we need `linux` _(lowercase)_
- `${VERSION:1} is cause of `Bad …
=> system version fix

cmd/stop_test.go, internal/digraph/builder_test.go, internal/digraph/executor/command.go, internal/digraph/executor/docker.go, internal/digraph/scheduler/data.go, internal/digraph/scheduler/graph.go, internal/digraph/scheduler/node.go, internal/digraph/scheduler/node_test.go, internal/digraph/scheduler/scheduler.go, internal/digraph/scheduler/scheduler_test.go, internal/integration/integration_test.go, internal/test/setup.go, internal/testdata/cmd/restart.yaml, internal/testdata/cmd/stop.yaml, internal/testdata/integration/environment-var.yaml, internal/testdata/integration/special-vars.yaml, internal/testdata/scheduler/start_stop.yaml
=> [#827] executor/docker: Fix: command arguments are not evaluated

.vscode/launch.json, docs/source/executors.rst, internal/digraph/executor/docker.go
=> [#830] executor/docker: support network configuration

CODE_OF_CONDUCT.md
Rewrite the document for style and clarity. 
Add a summary of Go Community CoC. 
Add a note to send us PR in case of any discrepencies.
=> doc: Update code of conduct

docs/source/contrib.rst
This commit improves the contribution guide by adding sections for support questions, reporting issues and additional documentation code contribution guidelines.
=> doc: improve contribution guide, add commit standards

README.md, cmd/config.go, cmd/retry.go, cmd/retry_test.go, cmd/start.go, docs/source/cli.rst, internal/client/client.go, internal/digraph/executor/sub.go, internal/integration/integration_test.go, internal/test/setup.go, internal/testdata/integration/call-sub.yaml, internal/testdata/integration/sub.yaml
Issue: #846 
Changes: 
- Fixed the Request ID parameter flag name
- Added integration test for calling sub-DAG
=> [#846] Fix: issue in calling sub-DAG

docs/source/config.rst, internal/config/config.go, internal/config/config_test.go, internal/config/loader.go, internal/frontend/frontend.go
Issue: #840
Changes:
- Added `dagsDir` config key
- Added tests for config load
- Added todo for config refactor
=> [#840] config: fix: Add `dagsDir` config key

docs/source/quickstart.rst
See: https://github.com/dagu-org/dagu/issues/841#issuecomment-2668916859
This I hope is a tiny edit, which would have answered some questions I had about output.
I might ask if this is successful to also add some docs to the output command, documenting some alternative patterns.
This is the kind of thing I encounter at work all the time. Some third party component that has noise in it's output, but maybe isn't OpenSource or is retrieving data from somewhere that means I need to make a tool to clean the data.
=> docs: update quickstart to include messy output example

docs/source/quickstart.rst
See https://github.com/dagu-org/dagu/issues/841
Just a note-block for now.
I noticed the other `note:` was not a note block, but managed to find an example in rest.rst of how this project was setup.
When testing I did use python 3.11.9 instead of 3.7.16 (which I think was old in 2018 😄 )
I can add changing the python version to this, but it might be better to have in it's own PR and issue so others can discuss.
=> docs: note block in execute the DAG of QuickStart

.goreleaser.yaml
Minor change to prevent warnings in goreleaser healthcheck
https://goreleaser.com/deprecations/#snapshotname_template
Fix #869
=> fix: snapshot deprecated warning (Fixes #869)

README.md
Closes https://github.com/dagu-org/dagu/issues/873#issuecomment-2708754362
=> docs: fixed incorrect command syntax in slack notification example

internal/digraph/builder.go, internal/digraph/scheduler/node.go, internal/mailer/mailer.go, schemas/dag.schema.json
**Changes:**
- Convert line breaks of email contents to `<br />`
- Fix json schema
- Handle `$` prefix in output name in DAG spec
=> executor/mail: fix: line breaks in email body are not properly converted to `<br />`

.github/workflows/docker.yaml, Dockerfile.alpine, Dockerfile.dev
Hi, I'm back with my work update! As discussed in issue #891, I've migrated the `dagu:latest` image to a `dagu:dev` version (which includes various development tools that are unnecessary in production), and created a new Alpine-based image `dagu:alpine`.
After setting up GitHub Actions in my forked repository and building the three images, pulling them to my server resulted in significant size reduction and build time improvements:
```
jerry@docker:~$ docker images | grep dagu
ghcr.io/jerry-yuan/dagu   dev               097d153d8388   27 minutes ago   1.39GB
ghcr.io/jerry-yuan/dagu   latest            9af316925576   29 minutes ago   126MB
ghcr.io/jerry-yuan/dagu   alpine            73a5aa5de41f   30 minutes ago   58MB
jerry@docker:~$ 
```
Additionally, I've tested most sample workflows. …
=> Optimize Docker image size and split into three base-line image

ui/src/components/atoms/Mermaid.tsx, ui/src/components/molecules/Graph.tsx, ui/tsconfig.json
added zoom in zoom out in mermaid.tsx for navigating through huge DAGs.
=> added zoom in zoom out for DAGs. #774

docs/source/yaml_format.rst, internal/digraph/builder.go, internal/digraph/scheduler/node.go, internal/digraph/scheduler/scheduler.go, internal/digraph/spec.go, internal/digraph/step.go, schemas/dag.schema.json
This PR adds support for specifying custom exit codes that should trigger task retries. Previously, the retry policy would retry on any non-zero exit code. Now users can specify exactly which exit codes should trigger retries, while other non-zero exit codes will cause the task to fail immediately.
1. Added `exitCode` field to the retry policy schema in `schemas/dag.schema.json`
2. Updated `RetryPolicy` struct in `internal/digraph/step.go` to include `ExitCodes` field
3. Added `ExitCode` field to `retryPolicyDef` struct in `internal/digraph/spec.go`
4. Updated builder in `internal/digraph/builder.go` to handle the new `exitCode` field
5. Enhanced exit code handling in `internal/digraph/scheduler/scheduler.go`:
- Added robust exit code extraction from different error types
- Added support …
=> added support for custom exit codes on retry #792

internal/cmd/context.go, internal/cmd/setup_test.go, internal/config/config_test.go, internal/digraph/executor/mail_test.go, internal/fileutil/fileutil.go, internal/fileutil/resolver_test.go, internal/integration/servercmd_test.go, internal/integration/startcmd_test.go, internal/persistence/jsondb/record.go, internal/persistence/jsondb/record_test.go, internal/persistence/local/dagstore.go, internal/persistence/local/storage/storage.go
This PR improves the security posture of the Dagu project by implementing more restrictive file and directory permissions throughout the codebase. The main changes include:
- Changed file permissions from 0644 (rw-r--r--) to 0600 (rw-r-----) across all file operations
- Changed directory permissions from 0755 (rwxr-xr-x) to 0750 (rwxr-x---)
=> Improve security by updating file and directory permissions

.github/workflows/docker-next.yaml, README.md
This PR:
- Adds `.github/workflows/docker-next.yaml` to build and publish Docker images from the `next` branch
- Updates README with a “Via Docker (next preview)” section showing how to pull `ghcr.io/dagu-org/dagu:next` and `next-<sha>` tags
- Does not add a new badge
**Note:** Preview images may contain breaking changes; pin to `next-<sha>` for a reproducible build.
=> ci: add docker-next workflow and docs for next preview image

internal/config/config_test.go, internal/config/loader.go
Issue: #926 
Changes:
- Fixed a bug in config loader where basic auth is not enabled when legacy config field is used.
=> [#926] fix: set basicauth flag correctly when legacy config key specified

internal/client/client.go, internal/config/loader.go, internal/digraph/executor/sub.go, internal/digraph/loader_test.go, internal/frontend/server/routes.go, internal/testdata/digraph/inherit_base.yaml, internal/testdata/digraph/inherit_child.yaml
Address the issue reported in #946 
Changes:
- Updated the server and scheduler to ensure the same config file is passed down to DAG executions.
=> [#946] fix: scheduler does not pass config file to DAG executions

internal/client/client.go
Follow-up for the bug fix in v1.16.11
=> [#946] fix: ensure the same config file is passed down to retry and restart execution as wel

internal/cmd/start.go, internal/persistence/filedagrun/store.go
- Skip queueing if no other process is running
- Fixed a minor issue where DAG-run list items order was not stable
=> [fb-1.17.0-beta] Start command should DAG-run without queueing when no other process

docs/source/base_config.rst, docs/source/cli.rst, docs/source/config.rst, docs/source/examples.rst, docs/source/intro.rst, docs/source/scheduler.rst, docs/source/schema.rst, docs/source/yaml_format.rst, internal/cmd/dequeue.go, internal/cmd/enqueue.go, internal/config/config.go, internal/config/config_test.go, internal/config/definition.go, internal/config/loader.go, internal/digraph/builder.go, internal/digraph/builder_test.go, internal/digraph/dag.go, internal/digraph/definition.go, internal/scheduler/queue_test.go, internal/scheduler/scheduler.go, internal/scheduler/scheduler_test.go, schemas/dag.schema.json
Resolves #992 
**Overview:**
- Added global queue config settings
```yaml
queues:
enabled: true # default is true
config:
- name: some_queue
maxActiveRuns: 3
```
- Added `queue` field as a DAG level field
```yaml
queue: global-queue
maxActiveRuns: 3
```
You can set it in the base DAG file to use same queue across all DAGs.
- Fixed a bug: default value (1) was not set for `maxActiveRuns` in DAG loading process
=> [#992] feat: implement queue configuration

internal/agent/reporter.go, internal/agent/reporter_test.go, internal/mailer/mailer.go, internal/mailer/mailer_test.go
It fixes HTML email table rendering issues in Gmail by implementing Gmail-compatible HTML structure and preventing automatic `newline-to-<br />` conversion for doctype HTML emails.
Addresses issue #996. Gmail was not rendering HTML email tables correctly due to incompatible HTML structure and unwanted newline processing that corrupted the table markup.
* Modified `renderHTML` function in `reporter.go` to generate Gmail-compatible HTML tables with proper structure and CSS styling.
* Added HTML content detection in `mailer.go` to prevent `newline-to-<br />` conversion for HTML documents with DOCTYPE declarations.
* Implemented proper HTML character escaping for security (e.g. XSS prevention).
* Added comprehensive unit tests to validate HTML output structure, content escaping, and email …
=> feat: enhance email HTML rendering

api/v1/api.gen.go, api/v1/api.yaml, api/v2/api.gen.go, api/v2/api.yaml, internal/agent/reporter.go, internal/cmd/status.go, internal/digraph/scheduler/scheduler.go, internal/digraph/scheduler/scheduler_test.go, internal/integration/parallel_test.go, internal/metrics/collector.go, internal/test/setup.go, ui/src/api/v2/schema.ts, ui/src/consts.ts, ui/src/pages/dag-runs/index.tsx, ui/src/pages/index.tsx, ui/src/ui/StatusChip.tsx
It implements a new `StatusPartialSuccess` enum value for DAG executions to handle scenarios where some nodes failed but were allowed to continue via continueOn.failure settings. The status indicates that primary work was completed despite some non-critical failures.
Addresses issue #1009 . Previously, DAG runs would show as `Failed` even when critical steps succeeded and only optional/non-critical steps failed with `continueOn.failure: true`. This made it difficult to distinguish between complete failures and successful runs with minor issues, reducing visibility into workflow health and success metrics.
* Added `StatusPartialSuccess = 6` to scheduler `Status` enum with "partial success" string representation
* Implemented `isPartialSuccess()` method in scheduler to detect when DAG has …
=> feat: add Partial Success status to DAG runs

internal/cmd/context.go, internal/frontend/api/v2/remote.go, internal/persistence/filedagrun/store.go, internal/persistence/filedagrun/store_test.go, internal/persistence/filequeue/reader_test.go, ui/index.html, ui/src/components/ui/date-range-picker.tsx, ui/src/features/dags/components/common/LiveSwitch.tsx, ui/src/features/dags/components/dag-editor/DAGEditButtons.tsx
- Fixed an issue where the remote node was not being set properly in the UI
- Fixed timezone handling issue where DAGs running at midnight in non-UTC timezones would incorrectly show as "Not Started" when `latestStatusToday` is enabled.
- When `latestStatusToday: true` is set, the system was using UTC time to determine "today" instead of the configured timezone. This caused DAGs that run at 00:00 in timezones like Europe/Paris (which is 22:00 UTC the previous day) to be considered as having run "yesterday" in UTC terms.
- Modified `internal/frontend/api/v2/remote.go` to fix node handling
- Fixed LiveSwitch component to properly handle node changes
- Added timezone location field to filedagrun Store
- Added WithLocation option to configure timezone when creating the store
- Updated …
=> [#1003,#999] fix(ui): set remote node properly

internal/digraph/scheduler/scheduler.go, internal/integration/repeat_on_exitcode_test.go, internal/testdata/integration/repeat-on-exitcode-fail.yaml
* Introduce case for repeat policy on non-zero exit codes to workflow/node success definition logic
Addresses issue #1051 . Previously although the repeat process was working correctly, nodes were marked as failed due to their non-zero exit code early, not allowing to account for exit codes repeat policy.
=> fix: repeat policy non zero exit codes

internal/digraph/scheduler/graph.go, internal/digraph/scheduler/node.go, internal/digraph/scheduler/scheduler.go
This PR refactors the graph Scheduler part of the codebase.
This was my best effort at improving the code with my current understanding by:
* splitting code into inner functions to improve readability
* rename misleading variables and functions 
* move code out of the scheduler into more fitting places, where possible
The Scheduler code has grown unwieldy after significant development done around the area, particularly aggravated by me adding repeat policies. This has become apparent in https://github.com/dagu-org/dagu/pull/1052 , where the complexity of the code made it difficult to fix an especially simple bug. I had to take responsibility and clean up after myself! 😁
=> feat(scheduler): refactor code and logic

internal/scheduler/scheduler.go, schemas/dag.schema.json
**Overview**
The DAG JSON schema had an incorrect definition for the `schedule` field. It only allowed a simple string, but the actual implementation supports multiple formats including arrays and objects with start/stop/restart schedules.
**Changes**
- Updated `schedule` field in `schemas/dag.schema.json` to properly support all valid formats:
- Single cron expression (string): `"0 1 * * *"`
- Multiple cron expressions (array): `["0 1 * * *", "0 13 * * *"]`
- Advanced scheduling (object): `{start: "0 8 * * *", stop: "0 18 * * *", restart: "0 12 * * *"}`
**Example**
```yaml
schedule: "0 1 * * *"
schedule:
- "0 1 * * *"
- "0 13 * * *"
schedule:
start: "0 8 * * MON-FRI"
stop: "0 18 * * MON-FRI"
restart: "0 12 * * MON-FRI"
```
=> fix: correct DAG JSON schema for schedule field

internal/digraph/builder.go, internal/digraph/builder_test.go, internal/digraph/definition.go, internal/digraph/scheduler/scheduler.go, internal/digraph/scheduler/scheduler_test.go, internal/digraph/step.go, internal/frontend/api/v1/dags.go, internal/frontend/api/v2/transformer.go, internal/integration/repeat_test.go, internal/testdata/digraph/repeat_policy_backward_until.yaml, internal/testdata/digraph/repeat_policy_backward_while.yaml, internal/testdata/digraph/repeat_policy_until_condition.yaml, internal/testdata/digraph/repeat_policy_until_exitcode.yaml, internal/testdata/digraph/repeat_policy_while_condition.yaml, internal/testdata/digraph/repeat_policy_while_exitcode.yaml, internal/testdata/integration/repeat-backward-compatibility-true.yaml, internal/testdata/integration/repeat-limit-condition.yaml, internal/testdata/integration/repeat-until-unconditional.yaml, internal/testdata/integration/repeat-while-unconditional.yaml, schemas/dag.schema.json
Still in draft because PR has Todos.
Todo:
* ensure tests for all repeat behaviors (both implicit and explicit)
* add validation for when `while`/`until` is used to always be accompanied by a `condition` or `exitCode`
Behaviour:
1. **Mode is omitted** (backwards compatibility)
* condition and expected are set: mode defaults to `until` 
* condition/exitcode are set: default to `while` 
2. **Mode is `while`:** 
* \+ condition & expected: repeats as long as the condition matches the expected value
* \+ condition: repeats as long as the condition evaluates successfully
* \+ exit code: repeats as long as step exit code matches any in the list
* neither: repeats as long as the step execution succeeds (no execErr)
3. **Mode is `until`**: vice versa
4. **Mode is `true`**: executes as a `while` …
=> feat: enhance repeat policy with while until

docs/features/executors/shell.md, internal/digraph/executor/command.go, internal/digraph/executor/command_errexit_simple_test.go, spec/ERREXIT_FLAG_IMPLEMENTATION.md
**Overview:**
Users need to prevent multi-line shell scripts from continuing execution after a command fails. They have to manually add `set -e` to every script to ensure failures stop execution.
As a solution, Dagu now automatically enables the errexit flag (`-e`) for default shell executors, making scripts fail-fast by default while respecting user choices when they specify a shell.
Issue: #1081
**Changes:**
- Add `-e` flag to default shell when no shell is specified by user
- Respect user's exact shell choice when `shell:` field is set
- Special handling for nix-shell (prepend `set -e;` to commands)
- Add comprehensive tests for errexit behavior
- Update documentation to explain new default behavior
**Example:**
```yaml
steps:
- name: safe-by-default
command: |
false  # This will cause …
```
=> [#1081] feat: enable errexit flag by default for shell executors

internal/cmd/context.go, internal/config/config.go, internal/config/definition.go, internal/config/loader.go, internal/scheduler/scheduler.go, internal/scheduler/scheduler_test.go, internal/scheduler/setup_test.go
This PR adds directory-level file-based locking for multiple scheduler instances.
It addresses issue https://github.com/dagu-org/dagu/issues/1055, and implicitly protecting against similar issues to https://github.com/dagu-org/dagu/issues/1054.
- Added `SchedulerLockStaleThreshold` and `SchedulerLockRetryInterval` config vars.
- Updated scheduler initialization and start methods to handle locking.
- Added tests to verify scheduler lock functionality and its helper methods.
=> feat(scheduler): implement directory locking for scheduler instances

internal/agent/progress_tea.go, internal/stringutil/duration.go, internal/stringutil/duration_test.go
Users experienced two display issues in the terminal progress view. The box border's closing `|` character was misaligned by 2 characters, and long-running steps showed incorrect elapsed times like "2562047h 47m" when the start time wasn't properly initialized.
This PR fixes both issues with minimal changes to ensure the terminal UI displays correctly.
Feedback-from: @yurivish
**Changes:**
- Fixed box border alignment by removing incorrect padding adjustment
- Added zero-time check to prevent displaying time since Unix epoch
- Both fixes are one-line changes in `progress_tea.go`
**Example:**
Before:
```
┌─ DAG: long ────────────────────────────────────────────────────────────────────┐
│ Status: Running ● | Started: 12:30:34 | Elapsed: 5.1s                            │
│ Run ID: …
```
=> fix: correct terminal UI display issues in progress view

CLAUDE.md, api/v1/api.yaml, api/v2/api.gen.go, api/v2/api.yaml, docs/features/execution-control.md, docs/index.md, docs/reference/yaml.md, docs/writing-workflows/control-flow.md, docs/writing-workflows/error-handling.md, docs/writing-workflows/examples.md, internal/digraph/builder.go, internal/digraph/builder_test.go, internal/digraph/definition.go, internal/digraph/scheduler/scheduler.go, internal/digraph/step.go, internal/integration/backoff_test.go, internal/testdata/digraph/repeat_policy_backoff.yaml, internal/testdata/digraph/repeat_policy_backoff_bool.yaml, internal/testdata/digraph/retry_policy_backoff.yaml, internal/testdata/digraph/retry_policy_backoff_bool.yaml, internal/testdata/integration/repeat-with-backoff-max.yaml, internal/testdata/integration/repeat-with-backoff.yaml, internal/testdata/integration/retry-with-backoff-bool.yaml, internal/testdata/integration/retry-with-backoff-max.yaml, internal/testdata/integration/retry-with-backoff.yaml, schemas/dag.schema.json
Users need exponential backoff to avoid overwhelming failed services with constant retry intervals. They have to manually implement increasing delays or risk causing cascading failures.
As a solution, this PR adds a `backoff` field to retry and repeat policies that automatically increases intervals exponentially, with an optional `maxIntervalSec` cap.
Follow-up to: #1093
**Changes**
- Added `backoff` field (float64) to RetryPolicy and RepeatPolicy structs
- Added `maxIntervalSec` field to cap exponential growth
- Implemented backoff calculation with formula: `interval * (backoff ^ attemptCount)`
- Support for boolean backoff (`true` = 2.0 default multiplier)
- Added validation that backoff must be > 1.0
- Updated API schemas (v1 and v2) and JSON schema
- Added comprehensive integration …
=> feat: add exponential backoff support for retry and repeat policies

internal/agent/dbclient_test.go, internal/cmd/dequeue.go, internal/cmd/dequeue_test.go, internal/integration/parallel_test.go, internal/metrics/collector_test.go, internal/models/dagrun.go, internal/models/dagrun_test.go, internal/persistence/filedagrun/attempt.go, internal/persistence/filedagrun/attempt_test.go, internal/persistence/filedagrun/dagrun.go, internal/persistence/filedagrun/dagrun_test.go, internal/persistence/filedagrun/dataroot.go, internal/persistence/filedagrun/store.go, internal/scheduler/scheduler.go, internal/testdata/cmd/dequeue_preserves_state.yaml, ui/src/pages/dag-runs/dag-run/index.tsx
When a DAG run is dequeued, it now preserves the previous successful state visibility instead of showing only 'Canceled'.
Issue: #1117
**Changes:**
- Added Hide() and Hidden() methods to DAGRunAttempt interface
- Implemented directory-based hiding using dot prefix convention
- Updated dequeue command to cancel and hide attempts
- Fixed UI to show proper error message for 404 errors on dequeued runs
=> fix: preserve previous DAG state when dequeuing

ui/src/features/dags/components/common/DAGActions.tsx, ui/src/features/dags/components/dag-execution/StartDAGModal.tsx, ui/src/layouts/Layout.tsx, ui/src/menu.tsx
This PR addresses two UI improvement requests from user feedback to enhance the user experience.
Issue: #1110 and #1104
Feedback-from: @ghansham and @ghansham_san
**Changes:**
- Removed the Start button from DAG actions, keeping only Enqueue button with play icon
- Replaced automatic hover-based sidebar expansion with manual toggle control
- Added localStorage persistence for sidebar state
- Implemented smooth transitions (200ms) for better UX
- Added interactive toggle button that shows Dagu icon when collapsed, panel icon on hover
**Why:**
1. The Start button didn't respect queue configuration while Enqueue did, causing confusion
2. The sidebar's automatic hover expansion was too sensitive and annoying for users
3. Users wanted more control over the UI layout with persistent preferences …
=> UI improvements: Simplify DAG execution and add manual sidebar toggle

internal/frontend/api/v2/dags.go, internal/models/paginator.go
hardcoding value 10000 generates issue and only shows top 200 dags while listing.
https://github.com/dagu-org/dagu/blob/111594fdd6186db2643f65661cabcc751f944702/internal/frontend/api/v2/dags.go#L320
changed this value of 10000 with 
`maxInt := int(^uint(0) >> 1)`
=> removed harcoded value of 10000 in models.NewPaginator

design/20_implemented/scheduler-health-check-requirements.md, docs/configurations/reference.md, docs/features/scheduling.md, internal/cmd/startall.go, internal/config/config.go, internal/config/config_test.go, internal/config/definition.go, internal/config/loader.go, internal/config/loader_test.go, internal/scheduler/health.go, internal/scheduler/health_test.go, internal/scheduler/scheduler.go
**Overview:**
Users need to monitor scheduler health status for production deployments. They currently have no way to check if the scheduler is running properly.
This PR adds a simple HTTP health check endpoint to the scheduler that monitoring tools can use.
Issue: #1120
**Changes:**
- Add `scheduler.port` configuration field (default: 8090)
- Implement `/health` endpoint that returns `{"status": "healthy"}`
- Health server only runs with `dagu scheduler` command, not `dagu start-all`
- Support `DAGU_SCHEDULER_PORT` environment variable
- Can disable health check by setting port to 0
**Example:**
```yaml
scheduler:
port: 8090  # Health check port (default)
```
```bash
dagu scheduler
curl http://localhost:8090/health
```
=> Add health check endpoint for scheduler

ui/src/features/dags/components/dag-list/DAGTable.tsx
**Overview:**
Users encountered a bug where DAG run durations displayed as "undefinedd undefinedh 1m" instead of showing the correct duration format. This occurred when the custom dayjs duration format function received certain date values.
The root cause was that the custom format function in `dayjs.ts` wasn't properly handling cases where duration methods returned undefined values, leading to malformed output strings.
Issue: #1136
Feedback-from: @yurivish
**Changes:**
- Replace custom dayjs format function with manual duration formatting in DAGTable.tsx
- Add date validation using `dayjs.isValid()` before calculating durations
- Implement cleaner duration display that only shows non-zero time units
- Remove debugging console.log statements
**Why:**
The custom format function was fragile …
=> fix: duration display shows 'undefinedd undefinedh' for invalid dates

CLAUDE.md, README.md, docs/reference/yaml.md, docs/writing-workflows/basics.md, docs/writing-workflows/data-variables.md, internal/digraph/builder.go, internal/digraph/builder_test.go, internal/digraph/definition.go, internal/digraph/scheduler/scheduler.go, internal/digraph/step.go, internal/integration/config_test.go, schemas/dag.schema.json
Refs: #1146 
This PR adds support for step-level environment variables. Example:
```yaml
env:
- FOO: "global_value"
steps:
- name: step1
env:
FOO: "step1_value"
command: echo $FOO # step1_value
```
=> [#1146] feat: implement step-level environment variables

internal/agent/agent.go, internal/cmd/start.go, internal/dagrun/manager.go, internal/digraph/dag.go, internal/persistence/fileproc/store_test.go, internal/scheduler/scheduler.go
Issue: #1130
Reported by @jonasban and @ghansham
When a user enqueues a dag from dag definition page, although initial steps are running but dag status is shown failed.
The `dagrun.Manager`'s `LatestStatus` method incorrectly use `DAG.Name` to retrieve running process from the process store where it needs to use `DAG.Queue` when the queue field is not empty.
https://github.com/dagu-org/dagu/blob/1e0d9451e74e83174e06d68bde8468047cda1a57/internal/dagrun/manager.go#L380-L392
It only reproduce when DAG.Queue is not emtpy.
- Fixed it to pass DAG.Queue instead of DAG.Name
- Fixed similar places as well
- Fixed the method name `DAG.QueueName` to `DAG.QueueProcName` to be more descriptive and minimize the chance of confusion
=> fix: proc store requires queue name when it's specified

Dockerfile, Dockerfile.alpine, Dockerfile.dev
**Changes**
- Fixes permission issues by creating DAGU_HOME directory with proper ownership during Docker build
- Applies fix to all Docker variants (standard, alpine, dev)
**Why**
- The `DAGU_HOME` directory (/var/lib/dagu) was not being created with proper permissions during the Docker build process. This caused permission denied errors when the dagu user attempted to write DAG files or execution data at runtime.
=> fix: ensure DAGU_HOME directory has proper permissions in Docker containers

ui/src/features/dags/components/common/DAGActions.tsx
Automatically navigate to DAG-run detail page after starting or enqueuing a DAG to show execution status.
=> feat: navigate to DAG-run detail page after execution

internal/agent/agent.go, internal/cmd/start.go, internal/config/config_test.go, internal/dagrun/manager.go, internal/digraph/builder_test.go, internal/digraph/dag.go, internal/models/proc.go, internal/persistence/fileproc/procgrp.go, internal/persistence/fileproc/store.go, internal/persistence/fileproc/store_test.go, internal/scheduler/queue_test.go, internal/scheduler/scheduler.go, internal/scheduler/zombie_detector.go, internal/scheduler/zombie_detector_test.go, internal/test/setup.go
Refactored proc store to use hierarchical directory structure separating group names (queues) from DAG names.
=> refactor: separate proc group name from dag name for better queue management

internal/cmd/coordinator.go, internal/coordinator/service.go, internal/test/coordinator.go
The coordinator service should register its host names instead of IP addresses in the service registry so that other nodes can access them.
Issue: #1187
=> [#1187] fix: register configured host name instead of resolved IP

internal/cmd/enqueue.go, internal/cmd/retry.go, internal/cmd/start.go, internal/frontend/api/v2/dagruns.go, internal/frontend/api/v2/dags.go, internal/scheduler/scheduler.go
For enqueue pass, we don't need to check whether active runs is exceeded if `maxActiveRuns <= 1` because the only cap will be the queue level `maxConcurrency` limit.
=> feat: improve check logic for `maxActiveRuns`

internal/cmd/agent_executor.go, internal/cmd/context.go, internal/cmd/start.go, internal/cmdutil/eval.go, internal/cmdutil/eval_test.go
- Fix the issue proc handle is not removed when a DAG execution failed with error due to os.Exit call
- Fix variable parsing issue
=> fix: proc handle is not removed when a DAG failed with error

docs/features/executors/docker.md, docs/reference/executors.md, docs/writing-workflows/container.md, internal/container/client.go, internal/container/client_test.go
- Harden Docker executor and DAG-level container behavior with clear validation and predictable execution semantics.
- Align and expand documentation to reflect required fields and formats.
=> feat(container): validate executor + dag container
