dagu-org/dagu

internal/admin/handlers/list.go, internal/admin/handlers/web/templates/index.gohtml, internal/controller/controller.go, internal/controller/controller_test.go, internal/sock/client.go, internal/sock/client_test.go, internal/sock/server.go, internal/sock/server_test.go
=> Add unix socket timeout on local client

cmd/retry_test.go, internal/agent/agent.go, internal/controller/controller.go, internal/database/database.go, internal/database/database_test.go, internal/database/writer.go, internal/reporter/reporter.go
=> Data compaction on job finish

Makefile, README.md, internal/agent/agent.go, internal/database/database.go, internal/database/database_test.go, internal/scheduler/node.go, internal/utils/utils.go, internal/utils/utils_test.go
Hi @lrampa, I am goint to update the file names a bit! If you have noticed anything, please file another issue/PR! Thanks !
=> Fix name of log files and data files to be the same order with their timestamps

README.md
リンクの変更以外にも、スペースが削除されている差分が出ていますが、私のローカルPCでのMarkdownファイル保存時の設定のようです。
=> READMEのreleaseページへのリンクが404だったので変更しました🙇

internal/admin/handlers/dag.go, internal/admin/handlers/list.go, internal/admin/http_test.go, internal/admin/loader.go, internal/config/loader.go, internal/controller/controller.go, internal/controller/controller_test.go, internal/database/database.go, internal/database/database_test.go, internal/scheduler/scheduler_test.go, internal/sock/client_test.go, internal/sock/server.go, internal/sock/server_test.go, internal/utils/utils.go, internal/utils/utils_test.go
https://github.com/yohamta/dagu/pull/92#issue-1236721791 のリベンジです🙇よろしければ取り込んでください🙋
=> Update ioutil -> io, os

README.md, internal/agent/agent_test.go, internal/config/config.go, internal/config/definition.go, internal/config/step.go, internal/controller/controller_test.go, internal/scheduler/node.go, internal/scheduler/node_test.go, internal/scheduler/scheduler.go, internal/scheduler/scheduler_test.go
=> fix: do not send error mail when it is canceled by user

README.md, internal/scheduler/node.go, internal/scheduler/node_test.go, internal/scheduler/scheduler.go, internal/scheduler/scheduler_test.go
fix: detect teardown() error in case something went wrong on writing to file
=> fix: detect error on node teardown()

internal/admin/handlers/dag.go, internal/admin/handlers/web/templates/dag.gohtml, internal/models/node.go, internal/models/node_test.go
It's necessary to enable us to create the live workflow editor
=> refactor: generate Mermaid graph with javascript

README.md, internal/config/config.go, internal/config/config_test.go, internal/config/definition.go, internal/runner/job.go, internal/runner/job_test.go, internal/runner/runner.go, internal/runner/runner_test.go
Example:
```yaml
schedule:
- "0 8 * * *"
- "30 9 * * *"
```
=> feat: allow setting multiple schedules

Makefile, go.mod, go.sum, internal/admin/handlers/web/templates/base.gohtml, internal/utils/utils.go
- Use go-shellwords fix command params issue.
- Allow set web page title.
=> Fix command params issue

admin/src/components/ConfigInfoTable.tsx, admin/src/components/DAGActions.tsx, admin/src/components/DAGHistory.tsx, admin/src/components/DAGLog.tsx, admin/src/components/DAGTable.tsx, admin/src/pages/DAGDetails.tsx, agent.go
- Fixed typo
- Change wrong subtitle on history page
- Add `Start` button to the DAG detail page for convenience
- Fix expand button on DAG list page visible
- Fix sorted label on DAG list page visible
=> Fix issues of Web UI

go.mod, go.sum, internal/config/config.go, internal/config/definition.go, internal/config/step.go, internal/executor/command.go, internal/executor/executor.go, internal/executor/http.go, internal/scheduler/graph.go, internal/scheduler/node.go, internal/scheduler/node_test.go, internal/scheduler/scheduler.go
=> Add executor interface

go.mod, internal/scheduler/node.go, internal/scheduler/node_test.go, internal/utils/utils.go
=> Fix command parsing issue

agent_test.go, cmd/dagu.go, cmd/dry.go, cmd/retry.go, cmd/start.go, cmd/status.go, cmd/stop.go, internal/admin/config.go, internal/admin/config_test.go, internal/admin/definition.go, internal/admin/errors_test.go, internal/admin/handler_test.go, internal/admin/loader.go, internal/config/config_test.go, internal/config/loader.go, internal/config/loader_test.go, internal/controller/controller.go, internal/controller/controller_test.go, internal/settings/settings.go
=> admin: add `baseConfig` option

cmd/dagu.go, internal/admin/loader_test.go, internal/settings/settings.go, internal/settings/settings_test.go
=> all: add `DAGU_HOME` env config

cmd/dagu.go, cmd/dagu_test.go, cmd/dry.go, cmd/retry.go, cmd/retry_test.go, cmd/scheduler.go, cmd/server.go, cmd/start.go, cmd/start_test.go, cmd/status.go, cmd/stop.go, internal/admin/config.go, tests/testdata/cmd_start_global_config.yaml, tests/testdata/cmd_start_global_config_base.yaml, tests/testdata/cmd_start_global_config_check.yaml
=> cmd: Add `--config=<admin config file>` option to all subcommands

admin/index.html, admin/src/Layout.tsx, admin/src/components/atoms/Mermaid.tsx, admin/src/components/atoms/StatusChip.tsx, admin/src/components/molecules/Graph.tsx, admin/src/components/molecules/NodeStatusChip.tsx, admin/src/components/organizations/DAGSpec.tsx, admin/src/consts.ts, examples/calling_subdag_main.yaml
just wanted to get rid of Mermaid smell. maybe theme option would be great to add in the future.
=> admin-web: update graph to be more stylish

admin/src/components/organizations/ExecutionHistory.tsx, admin/src/pages/dags/dag/index.tsx, examples/example.yaml, go.mod, go.sum, internal/admin/handlers/dag.go
=> admin-web: fix execution history sorting issue

README.md, internal/dag/dag.go
Default DAG's Log Dir
Current: `${DAG_HOME}/logs/${name}/${name}`
Update: `${DAG_HOME}/logs/dags/${name}`
Let DAG's default log dir keep consistent with admin's: `${DAG_HOME}/logs/admin`
=> update default dag log dir

README.md, agent.go, agent_test.go, internal/dag/dag.go, internal/dag/definition.go, internal/dag/loader_test.go, internal/dag/step.go, internal/scheduler/node.go, internal/scheduler/node_test.go, internal/scheduler/scheduler.go, internal/scheduler/scheduler_test.go
=> internal/dag: add signalOnStop

admin/package.json, admin/yarn.lock
Upgrading react-table version fixes some of the issues in admin web UI.
=> admin-web: upgrade react-table version

admin/src/components/molecules/DAGActions.tsx, internal/admin/handlers/dag.go
close https://github.com/yohamta/dagu/issues/215
=> allow parameters to be given on start button

internal/dag/dag.go, internal/dag/definition.go, internal/dag/step.go
=> internal/dag: add executorConfig to `Step`

agent.go, examples/stopOnSignal.yaml
=> Fix signalOnStop bug

examples/docker-container.yaml, go.mod, go.sum, internal/executor/docker.go
=> Add docker executor boilerplate

internal/admin/handlers/dag.go, internal/dag/dag.go, internal/dag/dag_test.go, internal/dag/definition.go, internal/dag/step.go, internal/executor/docker.go, internal/executor/executor.go, internal/runner/agent_test.go
Example 1:
```yaml
steps:
- name: S1
executor: http
```
Example 2:
```yaml
steps:
- name: S1
executor:
type: http
timeout: 1
```
=> Refactor executor config type

internal/dag/definition.go
Issue [#234 ](https://github.com/yohamta/dagu/issues/234)
=> Add env field to step in DAG spec

README.md
updated the README to the renamed example filename
=> fix link to example

admin/src/components/molecules/DAGActions.tsx, admin/src/components/molecules/StartDAGModal.tsx, admin/src/lib/parseParams.ts, admin/src/pages/dags/index.tsx, internal/controller/controller.go, internal/dag/builder.go, internal/dag/builder_test.go, internal/utils/utils.go, internal/utils/utils_test.go
- Improve the parameter modal
- Handling a parameter that contains multiple lines
- Fix a bug in UI
=> Improve parameter input modal

.gitignore, Makefile, cert/openssl.conf, internal/admin/http.go, internal/config/config.go
- #442
- Add `DAGU_CERT_FILE` and `DAGU_KEY_FILE` environment variables.
=> Add support for TLS for admin server

schemas/dag.schema.json
Related to https://github.com/dagu-dev/dagu/issues/325
=> Add Dagu DAG JSON schema

schemas/dag.schema.json
I missed the very important property "depends" on PR https://github.com/dagu-dev/dagu/pull/464
Same as #465 but with no merge conflicts
=> Improve dag.schema.json

internal/config/config.go
=> fix api base url to be the same host

service/frontend/fx.go
=> fix basic auth issue

internal/dag/builder.go, internal/dag/definition.go, internal/dag/mail.go, internal/executor/mail.go, internal/mailer/mailer.go, internal/reporter/reporter.go
Work in progress. Attach to send with auth is missing.
=> Add attach logs to report mail

README.md
Hi @yohamta.
I have added the `Cron expression generator link` for help. 
I think it is a useful link for our community and those who use `dagu`.
Thank you.
=> `Cron expression generator link` added into the scheduler for help.

Makefile
Resolves https://github.com/dagu-dev/dagu/issues/514
=> Force assets removal

scripts/downloader.sh
hello!
fix for this -> https://github.com/dagu-dev/dagu/issues/467
=> fix install script

Dockerfile
Update Dockerfile to fix issue #524
Update dagu version to 1.12.9 from 1.10.5
=> Update Dockerfile #524

Dockerfile, Makefile, internal/config/config.go, internal/scheduler/node.go
Fix binary format issue in Docker image.
#524 #434
=> fix: dockerfile

docs/source/config.rst
=> #543 Duplicate description removedcate description removed.

docs/source/api_token.rst
=> #544 Corrected documentation regarding Basic Authentication config.

internal/sock/server.go
=> Fix data race

internal/dag/loader.go
This PR fixes the following issue:
#567
=> Fix Config Loader Issue

internal/config/config.go, internal/dag/builder.go, internal/dag/loader.go, internal/executor/command.go, internal/scheduler/node.go, internal/scheduler/scheduler.go, internal/scheduler/scheduler_test.go, internal/utils/utils.go, internal/utils/utils_test.go
This PR fixes the scheduler behavior for DAGs. Now the DAGs inherit system environment variables.
=> Inherit system env

docs/source/yaml_format.rst
yaml timeout value should not have comma after integer 10
=> fix http timeout syntax

.github/workflows/ci.yaml
=> Update actions/cache from v3 to v4

internal/dag/executor/ssh.go, internal/dag/executor/ssh_test.go
=> [#674] Support env var in ssh config

docs/source/config.rst, docs/source/scheduler.rst, internal/frontend/middleware/global.go
=> Revert "docs: tiny adjustment on server configuration"

internal/frontend/middleware/global.go
Related:
- #718
- #720 
**Change overview**
- Modified the server middleware setup to clean the request path
=> Fix: frontend does not work when request path is not clean

.devcontainer/devcontainer.json, .gitattributes
I am developing on Windows, so it makes it easier to develop using devcontainers for this project.
=> chore: add support for devcontainers

cmd/common_test.go, cmd/dry_test.go, cmd/restart_test.go, cmd/retry_test.go, cmd/start_test.go, cmd/status_test.go, cmd/stop_test.go, internal/agent/agent_test.go, internal/client/client_test.go, internal/digraph/context.go, internal/digraph/executor/command.go, internal/digraph/executor/sub.go, internal/digraph/loader.go, internal/digraph/loader_test.go, internal/digraph/scheduler/graph.go, internal/digraph/scheduler/node.go, internal/digraph/scheduler/scheduler.go, internal/digraph/step.go, internal/fileutil/fileutil.go, internal/fileutil/fileutil_test.go, internal/frontend/dag/handler.go, internal/persistence/client/store_factory.go, internal/persistence/interface.go, internal/persistence/jsondb/jsondb.go, internal/persistence/jsondb/jsondb_test.go, internal/persistence/jsondb/setup_test.go, internal/persistence/jsondb/writer.go, internal/persistence/jsondb/writer_test.go, internal/persistence/local/dag_store.go
**Changes**
- Refactoring legacy code (round3)
- Optimized data handling for output variables reducing disk usage
=> Optimize data handling for output variables reducing JSON data size

cmd/retry.go, internal/agent/agent.go, internal/agent/agent_test.go, internal/agent/reporter.go, internal/agent/reporter_test.go, internal/client/client.go, internal/client/client_test.go, internal/client/interface.go, internal/digraph/builder.go, internal/digraph/context.go, internal/digraph/executor/command.go, internal/digraph/executor/sub.go, internal/digraph/scheduler/node.go, internal/digraph/scheduler/scheduler.go, internal/digraph/scheduler/scheduler_test.go, internal/digraph/step.go, internal/frontend/dag/convert.go, internal/frontend/dag/handler.go, internal/persistence/interface.go, internal/persistence/jsondb/jsondb.go, internal/persistence/jsondb/jsondb_test.go, internal/persistence/jsondb/setup_test.go, internal/persistence/jsondb/writer.go, internal/persistence/jsondb/writer_test.go, internal/persistence/model/status.go, internal/persistence/model/status_test.go
- persistence: Fixed to avoid saving `Variables` field data of DAG steps as they're unnecessary
- chore: Cleaned up old code
=> persistence: refactor: Avoid persisting unnecessary data of DAG steps

.github/workflows/release.yaml, Dockerfile, entrypoint.sh
- image: Changed the final base image from alpine to ubuntu
- image: Added basic handy tools to the final image
=> docker-image: Add handy tools to the base image

README.md, docs/source/yaml_format.rst, internal/digraph/builder.go, internal/digraph/errors.go, internal/digraph/spec.go, schemas/dag.schema.json
Example:
```yaml
steps:
step1:
command: echo hello
step2:
command: echo world
step3:
command: echo hello world
depends:
- step1
- step2
```
=> digraph: Allow a map for steps instead of a list

docs/source/config.rst, internal/config/config.go, internal/config/loader.go, internal/frontend/frontend.go
=> [#800] docs: headless mode

README.md
Removed the note about github discussions.
=> Remove Github Discussions

.github/workflows/release.yaml, .goreleaser.yaml, Makefile, internal/digraph/executor/mail.go
=> [#821] Support Snapcraft distribution

docs/source/executors.rst
Thank you for all the fast and hard work you made. I've tested and it worked really well 🥳. I send a small PR to clear some confusions in the document about the docker executor with environment variables.
=> doc(executor/docker): add doc about working with env

cmd/dry_test.go, cmd/retry_test.go, cmd/start_test.go, internal/agent/agent.go, internal/cmdutil/eval.go, internal/digraph/builder_test.go, internal/digraph/context.go, internal/digraph/context_step.go, internal/digraph/executor/command.go, internal/digraph/executor/mail_test.go, internal/digraph/params.go, internal/digraph/scheduler/node_test.go, internal/digraph/scheduler/scheduler_test.go, internal/integration/integration_test.go, internal/test/setup.go, internal/testdata/integration/env-script.yaml, internal/testdata/integration/jq.yaml, internal/testdata/integration/json_var.yaml, internal/testdata/integration/positional-params-script.yaml, internal/testdata/integration/positional-params.yaml
- Added more tests on parameter handling.
- Fixed bugs in positional parameter handling.
=> test: add integration tests

.github/FUNDING.yml
Introduce `FUNDING.yml` file. This adds a funding panel to the github repo. 
More information: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
=> doc: Add Github sponser button

ui/src/components/molecules/CreateDAGButton.tsx, ui/src/components/molecules/DAGEditButtons.tsx
Issue: #877
**Changes**
- Fixed the frontend code to ensure that the `basePath` setting is respected when routing.
=> [#877] ui: fix: base path is not working on web

internal/digraph/condition.go, internal/digraph/context_step.go, internal/digraph/executor/command.go, internal/digraph/executor/docker.go, internal/digraph/executor/http.go, internal/digraph/executor/jq.go, internal/digraph/scheduler/data.go, internal/digraph/scheduler/node.go
=> [#882] Fix context handling issue

docs/source/api_token.rst, docs/source/auth.rst, docs/source/config.rst, internal/config/loader.go, internal/fileutil/fileutil.go
=> [#880] config: fix: auth token issue

internal/config/loader.go
=> [#889] fix: config: Remote node with auth not working

README.md, internal/digraph/executor/command.go, internal/integration/dag_test.go, internal/testdata/integration/perl-script.yaml
=> [#893] fix: Multi-line Python script result in error

ui/src/components/atoms/Mermaid.tsx, ui/src/components/molecules/Graph.tsx, ui/src/components/organizations/DAGStatus.tsx
Addressing: #905 
**Changes**
- Removed the animation icons on graph to avoid the incomplete text issue.
- Fix an issue where graph position and zooming are reset when graph is updated while running the DAG.
**Updated version of the graph visualization**
=> [#905] DAG visualization updates

Dockerfile
**Changes:**
- Delete default ubuntu user to avoid conflict with dagu user
- Update sudoers setting
=> chore: Fix docker image

README.md, scripts/downloader.sh, scripts/installer.sh
- Add `--version` and `--install-dir` flags
- Update README with usage examples
=> feat: add `--version` and `--install-dir` options to `installer.sh`

internal/digraph/builder.go, internal/digraph/definition.go, internal/digraph/executor/command.go, internal/digraph/step.go, schemas/dag.schema.json
=> [#925] feat: Support nix shell

internal/scheduler/scheduler.go, ui/src/api/v2/schema.ts, ui/src/features/dags/components/dag-details/DAGStatusOverview.tsx, ui/src/features/dags/components/dag-details/NodeStatusTable.tsx, ui/src/features/dags/components/dag-editor/DAGEditButtons.tsx, ui/src/features/dags/components/dag-editor/DAGSpec.tsx, ui/src/features/dags/components/dag-execution/DAGExecutionHistory.tsx
Fixed some small issues in the scheduler for handling queue items with wrong statuses.
=> Fix: handle queue item with wrong status properly

.github/workflows/docker.yaml, internal/digraph/executor/docker.go, internal/persistence/fileproc/handle.go, internal/persistence/fileproc/procgrp.go
- Fix too long version name
- Fix other small issues
=> Fix: version name issue

internal/cmdutil/cmd.go, internal/dagrun/manager.go, internal/digraph/executor/command.go, internal/integration/definition_test.go, internal/testdata/integration/shellopts.yaml
- Fixed command executor to handle shell options.
=> [#967] fix: shell options are not working

internal/digraph/builder.go, internal/digraph/errors.go
Issue: #965
This PR removes step name validation to allow any characters.
=> [#965] fix: remove restrictive step name validation

README.md, docs/source/changelog.rst, docs/source/examples.rst, docs/source/parallel_execution.rst, docs/source/quickstart.rst, docs/source/yaml_format.rst, examples/chain_with_override.yaml, examples/chain_workflow.yaml, internal/digraph/builder.go, internal/digraph/builder_test.go, internal/digraph/dag.go, internal/digraph/definition.go, internal/digraph/step.go, internal/integration/chain_test.go, internal/testdata/digraph/chain_basic.yaml, internal/testdata/digraph/chain_no_dependencies.yaml, internal/testdata/digraph/chain_with_explicit_depends.yaml, internal/testdata/digraph/invalid_type.yaml, internal/testdata/integration/chain-basic.yaml, internal/testdata/integration/chain-explicit-depends.yaml, internal/testdata/integration/chain.yaml, internal/testdata/integration/skipped-preconditions.yaml, schemas/dag.schema.json, spec/SEQUENTIAL_STEP_EXECUTION.md
Resolves #998 
**Overview:**
- Implemented `type` field (allows `graph`(default) or `chain`)
- Updated documentation
=> [#998] feat: implement chain type

internal/dagrun/manager.go
- Add proper process cleanup by calling cmd.Wait() in goroutines after cmd.Start()
- Modified StartDAGRun, RestartDAG, and RetryDAGRun to wait for child processes
- Each cmd.Start() is now followed by a goroutine that calls cmd.Wait()
When cmd.Start() is called without a corresponding cmd.Wait(), the child process becomes a zombie after it terminates. 
Issue: #1013
=> [#1013] fix: prevent zombie processes in DAG execution

scripts/installer.sh
Added cases for different architecture to support rasberry pi.
Refs #1077 
Fixes #1077
=> Fix: corrected installer script issue

go.mod, go.sum, internal/config/config.go, internal/config/config_test.go, internal/config/definition.go, internal/config/loader.go, internal/frontend/api/v2/api.go, internal/frontend/auth/middleware.go, internal/frontend/auth/oidc.go, internal/frontend/server.go, internal/stringutil/stringutil.go
=> add support auth with oidc

ui/src/features/dags/components/dag-list/DAGTable.tsx
Fixes the next run where cron exp has CRON_TZ.
Refs #1083 
Fixes #1083
Testing proof
=> fixing next run for timezones

.github/workflows/manual-release.yaml, .github/workflows/npm-publish.yaml, .github/workflows/release.yaml, design/20_implemented/npm-distribution-design.md, docs/configurations/advanced.md, docs/features/executors/docker.md, docs/reference/executors.md
=> chore: upgrade node to 22

internal/dagrun/manager.go, internal/frontend/api/v2/dags.go, ui/package.json, ui/pnpm-lock.yaml, ui/src/components/ui/checkbox.tsx, ui/src/features/dags/components/common/DAGActions.tsx, ui/src/features/dags/components/dag-execution/StartDAGModal.tsx
Add checkbox to start DAGs immediately, bypassing the queue for urgent workflows.
=> feat: add immediate start option to bypass queue

README.md, docs/configurations/reference.md, docs/getting-started/quickstart.md, internal/cmd/context.go, internal/config/config.go, internal/config/loader.go, internal/persistence/filedag/examples.go, internal/persistence/filedag/store.go, internal/persistence/filedag/store_test.go, internal/test/scheduler.go, internal/test/setup.go
Automatically creates example DAG files when Dagu starts with an empty DAGs directory, helping new users get started quickly.
=> feat: auto-create example DAGs for new users

internal/config/loader.go, internal/coordinator/service.go, internal/digraph/builder.go, internal/digraph/command.go, internal/integration/config_test.go, internal/test/setup.go
Issue: #1203
This PR fixes issues in leading/trailing spaces in script field as well as other fields.
=> [#1203] Trim spaces

ui/src/components/DAGNameInputModal.tsx, ui/src/features/dags/components/common/CreateDAGButton.tsx, ui/src/features/dags/components/common/CreateDAGModal.tsx, ui/src/features/dags/components/dag-editor/DAGEditButtons.tsx, ui/src/lib/dag-validation.ts
Improve the DAG name input dialog so that it validates the user input before sending API request.
=> feat(ui): Input DAG name modal

api/v2/api.gen.go, api/v2/api.yaml, docs/reference/api.md, internal/frontend/api/v2/dags.go, ui/src/api/v2/schema.ts, ui/src/features/dags/components/common/DAGActions.tsx
=> feat: Add POST `/api/v2/dags/{dagName}/stop-all` endpont

internal/migration/migration.go
Fix migration command to skip entries that does not have `Status` or `StartedAt`.
If old history file to migrate doesn't have an empty timestamp, the system automatically assigns the current date and time, which makes it appear as the latest entry.
With this fix, the system will skip creating data entries without a valid timestamp or status, so the issue should no longer occur.
Feedback by @ghansham
=> fix: skip history data with empty status or started at

docs/configurations/deployment.md, docs/features/executors/docker.md, docs/getting-started/installation.md
Ref: #1228 
Feedback by @bellackn
=> doc: correct docker-in-docker example

ui/src/pages/system-status/index.tsx
=> [#1224] fix(ui): correct api params

api/v2/api.gen.go, api/v2/api.yaml, cmd/main.go, cmd/main_test.go, docs/getting-started/quickstart.md, docs/overview/api.md, docs/overview/cli.md, docs/reference/api.md, docs/reference/changelog.md, docs/reference/cli.md, internal/cmd/validate.go, internal/cmd/validate_test.go, internal/digraph/builder.go, internal/frontend/api/v2/dags.go, ui/src/api/v2/schema.ts
Add CLI command to validate DAG specs and new API endpoint to validate YAML without persisting.
=> feat(api, cmd): Add DAG validate command and API endpoint

internal/frontend/api/v2/dags.go, internal/persistence/filedag/store.go, ui/src/features/dags/components/dag-editor/DAGEditor.tsx, ui/src/features/dags/components/dag-editor/DAGSpec.tsx
Remove `Read/Edit` mode separation for the DAG spec editor.
=> feat(ui): improve DAG spec Ediotr

ui/src/features/dags/components/dag-list/DAGTable.tsx
=> fix(ui): display grouped DAGs

README.md, docs/configurations/deployment/macos.md, docs/getting-started/installation.md, docs/getting-started/quickstart.md, docs/index.md
- Update the installation documentation in favor of https://github.com/Homebrew/homebrew-core/pull/246088
=> doc: update brew installation fomula

internal/integration/parallel_test.go, internal/stringutil/stringutil.go, internal/stringutil/stringutil_test.go
=> fix: treat single JSON object as a parallel item

internal/digraph/scheduler/scheduler.go
=> fix: initialize node before setting node status running
